spring:
  application:
    name: fda-records-api

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:fdarecords
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# FDA API Configuration
fda:
  api:
    base-url: https://api.fda.gov/drug/drugsfda.json

# OpenFDA API Configuration
openfda:
  api:
    connect-timeout: 1000
    read-timeout: 1000

# Server Configuration
server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method